### PR TITLE
Added JsonRpc over Spring RestTemplate  (issue #67)

### PR DESCRIPTION
**Pull request by im-scooter**
Added base implementation for JsonRpc client over Spring RestTemplate (issue #67) .
I tried to avoid other code touching but...  made some refactoring. I hope you will find it useful.

[Review on Reviewable](https://reviewable.io/reviews/briandilley/jsonrpc4j/70)

### CODE REVIEW

**Comment by gaborbernat** [comment]
Thanks, unless @briandilley can look over this in the following days, it will take some time, as I would like to review this and I'm busy during the following days. Nevertheless, I'll note to look over it :+1: thanks again

**Comment by gaborbernat** [comment]
Hello, 

@im-scooter can you tell me a use case when this new addition comes handy. What's the problem you're trying to resolve with this? I'm referring what extra does it provide over the JsonRPCHttpClient.

Thanks,

**Comment by gaborbernat** [comment]
Review status: 0 of 44 files reviewed at latest revision, 13 unresolved discussions, some commit checks pending.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java, line 2 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviY1EmEs-wvGSPoyMN)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java#L2)):</sup>
Note JsonRpcParamName has been deprecated and removed since.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java, line 136 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviXF4XvPQAnc44kaEn)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L136)):</sup>
This logger modification could have been a separate pull request I feel, as it has nothing in common with the scope of this pull request.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java, line 405 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviXkzHl_NdFae4SzGc)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java#L405)):</sup>
formatting issue, use spaces around operators

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java, line 512 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYEAL-3JD8SZM61ah)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java#L512)):</sup>
what are these spaces, we use tabs, please change them

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java, line 61 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYWOAHFQFBngsRdFT)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java#L61)):</sup>
again restore tabs please

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java, line 113 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYdKoM9Jx-MF7AqaV)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java#L113)):</sup>
rewrite the documentation too as inherited if you created the interface, for all inherited methods, avoid duplication

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java, line 2 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYzBaPCZS406qzJxa)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java#L2)):</sup>
The license should be removed from the file, it's in the root of the project

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java, line 235 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZ7XTe85BxUKTTYsa)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java#L235)):</sup>
again I think here should be an inheritdoc entry

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/MappingJacksonRPC2HttpMessageConverter.java, line 43 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZGAZMYlUEF7Sb4fE)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/MappingJacksonRPC2HttpMessageConverter.java#L43)):</sup>
remove author, git already stores that, instead add some description what this classes does, in let's say 2 sentences

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java, line 17 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZQKQdZXMMe5-jN1T)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java#L17)):</sup>
remove license from file

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java, line 32 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZOKIU9mKT0_X7_D5)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java#L32)):</sup>
again, add a class comment

---

<sup>**[src/test/java/com/googlecode/jsonrpc4j/loadtest/JsonRpcServiceImpl.java, line 22 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZd6P_fqw4OMEYvEI)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/test/java/com/googlecode/jsonrpc4j/loadtest/JsonRpcServiceImpl.java#L22)):</sup>
formatting is off, this { should be on the same line as the function 

---

<sup>**[src/test/java/com/googlecode/jsonrpc4j/rest/loadtest/LoadRestTest.java, line 17 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZnL6RLF6BvRKcpFt)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/test/java/com/googlecode/jsonrpc4j/rest/loadtest/LoadRestTest.java#L17)):</sup>
remove author, will be in git

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by im-scooter** [comment]
Hello, Gábor Bernát.
The main advantage of transport across RestTemplate is ability of using application share  specific security constraint. That constraint we can manage with chain of ClientHttpRequestInterceptor's and ClientHttpRequestFactory. So the easest way to made all communications same for dedicated security domain.

**Comment by im-scooter** [comment]
Review status: 0 of 44 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java, line 2 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviY1EmEs-wvGSPoyMN)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java#L2)):</sup>
It out of my competence to decide what API is deprecated.  It is fully for for your view.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java, line 136 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviXF4XvPQAnc44kaEn)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L136)):</sup>
Ok, I can revert the logging changes. However this from is more efficient thus allows create resulting string directly before output (after level filtering etc.)

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java, line 405 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviXkzHl_NdFae4SzGc)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java#L405)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java, line 512 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYEAL-3JD8SZM61ah)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcClient.java#L512)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java, line 61 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYWOAHFQFBngsRdFT)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java#L61)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java, line 113 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYdKoM9Jx-MF7AqaV)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/JsonRpcHttpClient.java#L113)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java, line 235 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZ7XTe85BxUKTTYsa)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java#L235)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/MappingJacksonRPC2HttpMessageConverter.java, line 43 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZGAZMYlUEF7Sb4fE)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/MappingJacksonRPC2HttpMessageConverter.java#L43)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java, line 17 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZQKQdZXMMe5-jN1T)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java#L17)):</sup>
Done.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java, line 32 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZOKIU9mKT0_X7_D5)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/SslClientHttpRequestFactory.java#L32)):</sup>
Done.

---

<sup>**[src/test/java/com/googlecode/jsonrpc4j/loadtest/JsonRpcServiceImpl.java, line 22 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZd6P_fqw4OMEYvEI)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/test/java/com/googlecode/jsonrpc4j/loadtest/JsonRpcServiceImpl.java#L22)):</sup>
Done.

---

<sup>**[src/test/java/com/googlecode/jsonrpc4j/rest/loadtest/LoadRestTest.java, line 17 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviZnL6RLF6BvRKcpFt)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/test/java/com/googlecode/jsonrpc4j/rest/loadtest/LoadRestTest.java#L17)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by im-scooter** [comment]
Review status: 0 of 44 files reviewed at latest revision, 13 unresolved discussions, some commit checks failed.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java, line 2 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviYzBaPCZS406qzJxa)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/spring/rest/JsonRpcRestClient.java#L2)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by gaborbernat** [comment]
Review status: 0 of 44 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java, line 2 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviY1EmEs-wvGSPoyMN)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java#L2)):</sup>
it's already removed in master, you should just follow on with it in your code

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java, line 136 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviXF4XvPQAnc44kaEn)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L136)):</sup>
you can keep it this way, it's okay

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by gaborbernat** [comment]
Please also fix merge conflicts :)

**Comment by im-scooter** [comment]
Gábor Bernát, unfortunately I can not understand how to merge changes from master to my forked repository...

**Comment by im-scooter** [comment]
Review status: 0 of 44 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java, line 136 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviXF4XvPQAnc44kaEn)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/DefaultExceptionResolver.java#L136)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by im-scooter** [comment]
Review status: 0 of 45 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

<sup>**[src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java, line 2 \[r2\]](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70#-JviY1EmEs-wvGSPoyMN)** ([raw file](https://github.com/briandilley/jsonrpc4j/blob/ac23e871e03961b162d4bef43c121101eca508c0/src/main/java/com/googlecode/jsonrpc4j/annotations/JsonRpcParamName.java#L2)):</sup>
Done. Merged with master.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by gaborbernat** [comment]
Sadly it'st still not good, note the status below:

This branch has conflicts that must be resolved.

**Comment by gaborbernat** [comment]
Furthermore I don't think it's advisable to create the annotations package. Note that those may be used by people, inside their code. Making this change will brake their source code. Please fix that too.

**Comment by gaborbernat** [comment]
Furthermore I've think you swapped the order, you should have put your code on top of the current master, not the other way around.

**Comment by im-scooter** [comment]
Ok. Tomorrow I'll revert annotations to their previous package...
Some questions about merge:
I'v used instructions from here https://help.github.com/articles/syncing-a-fork/, what I did wrong?

**Comment by gaborbernat** [comment]
Hmm, good question. Not sure, but I feel like the method is correct just that the order is incorrect of what you did. If you add me as a collaborator to your fork I could try to take a look at it once you're restored the packages.

---

Reviewed 35 of 44 files at r1, 1 of 2 files at r2, 8 of 8 files at r3.
Review status: 39 of 45 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/briandilley/jsonrpc4j/70)

**Comment by im-scooter** [comment]
Hi, Gábor Bernát.
I have added you as collaborator to https://github.com/im-scooter/jsonrpc4j.

**Comment by im-scooter** [comment]
Repeated merge with master. Now branch can be merged without conflicts.

**Comment by wuwen5** [comment]
Hi @im-scooter, you can  [squashed](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request#squash-your-changes) your commits. :blush: 

Pull-requests MUST NOT contain intermediate commits (e.g., bug fixes to your own patch, refactoring of your own patch), which should be squashed and then force-pushed to your branch. Generally, fewer commits are better. However, it's acceptable for a PR to have multiple commits, each implementing specific distinct changes.

**Comment by im-scooter** [comment]
Hi? @wuwen5. I made pull request long ago. And, unfortunately, while wating.... I found some bugs :(

**Comment by gaborbernat** [comment]
You can use git rebase HEAD~15, and then force push the squash commits, :)

**Comment by im-scooter** [comment]
Commits has been squashed.

**Comment by gaborbernat** [comment]
will merge in, in the meantime still waiting for release rights from @briandilley

**Pull request merged**
